[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL =  "https://bank-account-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
